# Setup
#
title: Paul Spieker
description: >
  I am **Paul Spieker**, a Ruby on Rails and EmberJS enthusiast.
copyright: 2020 by Paul Spieker
url: https://paul.spieker.me
facebook_username: 'pspieker'
twitter_username: "paul_spieker"
linkedin_username: 'paul-spieker-86a0174a'
instagram_username: 'paulspieker'
github_username:  'spieker'
feed_icon: rss
email: 'paul@spieker.me'
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5

# SASS
#
sass:
  sass_dir: assets/sass

# Markdown
#
highlighter: rouge
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  :input:          GFM
  hard_wrap:      false
  footnote_nr:    1
